name: ðŸ—ƒï¸ Archive (Rename) MongoDB Collections

on:
  workflow_dispatch:
    inputs:       
      environment:
        description: 'Select the deployment environment'
        type: choice
        required: true
        default: 'test'
        options:
          - test
          - acc
          - prev
          - prod

      prefix:
        description: 'Prefix to append for renaming collections'
        required: true
        default: 'archived_'          

jobs:
  rename-collections:
    name: Rename Collections
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MongoDB Environment Variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        env:
          environment: ${{ github.event.inputs.environment }}

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build:all

      - name: List Build Directory #TEST TO CHECK IF COMPILATION WORKED
        run: ls -R .build
     
      - name: Run Collection Rename Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          node ./build/scripts/renameCollections.js "${{ github.event.inputs.prefix }}"          
